// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: proto/document.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DocumentClient is the client API for Document service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocumentClient interface {
	StoreDocument(ctx context.Context, opts ...grpc.CallOption) (Document_StoreDocumentClient, error)
	GetDocumentByReffNumber(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error)
	UpdateDocumentByReffNumber(ctx context.Context, in *UpdateDocumentRequest, opts ...grpc.CallOption) (*UpdateDocumentResponse, error)
	DeleteDocumentByReffNumber(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DeleteDocumentResponse, error)
	ListDocument(ctx context.Context, in *DocumentParameterRequest, opts ...grpc.CallOption) (*ListServiceDocumentResponse, error)
	RevokeDocument(ctx context.Context, in *RevokeDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error)
	UploadFileService(ctx context.Context, opts ...grpc.CallOption) (Document_UploadFileServiceClient, error)
	DownloadFileService(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (Document_DownloadFileServiceClient, error)
	GetInvoiceDocument(ctx context.Context, in *GetInvoiceDocumentRequest, opts ...grpc.CallOption) (*GetInvoiceDocumentResponse, error)
	GetSupportingDocument(ctx context.Context, in *GetSupportingDocumentRequest, opts ...grpc.CallOption) (*GetSupportingDocumentResponse, error)
	CreateInvoiceDocument(ctx context.Context, in *CreateInvoiceDocumentRequest, opts ...grpc.CallOption) (*CreateInvoiceDocumentResponse, error)
	CreateSupportingDocument(ctx context.Context, in *CreateSupportingDocumentRequest, opts ...grpc.CallOption) (*CreateSupportingDocumentResponse, error)
	UpdateInvoiceDocument(ctx context.Context, in *UpdateInvoiceDocumentRequest, opts ...grpc.CallOption) (*UpdateInvoiceDocumentResponse, error)
	UpdateSupportingDocument(ctx context.Context, in *UpdateSupportingDocumentRequest, opts ...grpc.CallOption) (*UpdateSupportingDocumentResponse, error)
}

type documentClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentClient(cc grpc.ClientConnInterface) DocumentClient {
	return &documentClient{cc}
}

func (c *documentClient) StoreDocument(ctx context.Context, opts ...grpc.CallOption) (Document_StoreDocumentClient, error) {
	stream, err := c.cc.NewStream(ctx, &Document_ServiceDesc.Streams[0], "/Document/StoreDocument", opts...)
	if err != nil {
		return nil, err
	}
	x := &documentStoreDocumentClient{stream}
	return x, nil
}

type Document_StoreDocumentClient interface {
	Send(*UploadDocRequest) error
	CloseAndRecv() (*UploadDocResponse, error)
	grpc.ClientStream
}

type documentStoreDocumentClient struct {
	grpc.ClientStream
}

func (x *documentStoreDocumentClient) Send(m *UploadDocRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *documentStoreDocumentClient) CloseAndRecv() (*UploadDocResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadDocResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *documentClient) GetDocumentByReffNumber(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error) {
	out := new(GetDocumentResponse)
	err := c.cc.Invoke(ctx, "/Document/GetDocumentByReffNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentClient) UpdateDocumentByReffNumber(ctx context.Context, in *UpdateDocumentRequest, opts ...grpc.CallOption) (*UpdateDocumentResponse, error) {
	out := new(UpdateDocumentResponse)
	err := c.cc.Invoke(ctx, "/Document/UpdateDocumentByReffNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentClient) DeleteDocumentByReffNumber(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DeleteDocumentResponse, error) {
	out := new(DeleteDocumentResponse)
	err := c.cc.Invoke(ctx, "/Document/DeleteDocumentByReffNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentClient) ListDocument(ctx context.Context, in *DocumentParameterRequest, opts ...grpc.CallOption) (*ListServiceDocumentResponse, error) {
	out := new(ListServiceDocumentResponse)
	err := c.cc.Invoke(ctx, "/Document/ListDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentClient) RevokeDocument(ctx context.Context, in *RevokeDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error) {
	out := new(GetDocumentResponse)
	err := c.cc.Invoke(ctx, "/Document/RevokeDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentClient) UploadFileService(ctx context.Context, opts ...grpc.CallOption) (Document_UploadFileServiceClient, error) {
	stream, err := c.cc.NewStream(ctx, &Document_ServiceDesc.Streams[1], "/Document/UploadFileService", opts...)
	if err != nil {
		return nil, err
	}
	x := &documentUploadFileServiceClient{stream}
	return x, nil
}

type Document_UploadFileServiceClient interface {
	Send(*UploadFileRequest) error
	CloseAndRecv() (*UploadFileResponse, error)
	grpc.ClientStream
}

type documentUploadFileServiceClient struct {
	grpc.ClientStream
}

func (x *documentUploadFileServiceClient) Send(m *UploadFileRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *documentUploadFileServiceClient) CloseAndRecv() (*UploadFileResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadFileResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *documentClient) DownloadFileService(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (Document_DownloadFileServiceClient, error) {
	stream, err := c.cc.NewStream(ctx, &Document_ServiceDesc.Streams[2], "/Document/DownloadFileService", opts...)
	if err != nil {
		return nil, err
	}
	x := &documentDownloadFileServiceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Document_DownloadFileServiceClient interface {
	Recv() (*DownloadFileResponse, error)
	grpc.ClientStream
}

type documentDownloadFileServiceClient struct {
	grpc.ClientStream
}

func (x *documentDownloadFileServiceClient) Recv() (*DownloadFileResponse, error) {
	m := new(DownloadFileResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *documentClient) GetInvoiceDocument(ctx context.Context, in *GetInvoiceDocumentRequest, opts ...grpc.CallOption) (*GetInvoiceDocumentResponse, error) {
	out := new(GetInvoiceDocumentResponse)
	err := c.cc.Invoke(ctx, "/Document/GetInvoiceDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentClient) GetSupportingDocument(ctx context.Context, in *GetSupportingDocumentRequest, opts ...grpc.CallOption) (*GetSupportingDocumentResponse, error) {
	out := new(GetSupportingDocumentResponse)
	err := c.cc.Invoke(ctx, "/Document/GetSupportingDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentClient) CreateInvoiceDocument(ctx context.Context, in *CreateInvoiceDocumentRequest, opts ...grpc.CallOption) (*CreateInvoiceDocumentResponse, error) {
	out := new(CreateInvoiceDocumentResponse)
	err := c.cc.Invoke(ctx, "/Document/CreateInvoiceDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentClient) CreateSupportingDocument(ctx context.Context, in *CreateSupportingDocumentRequest, opts ...grpc.CallOption) (*CreateSupportingDocumentResponse, error) {
	out := new(CreateSupportingDocumentResponse)
	err := c.cc.Invoke(ctx, "/Document/CreateSupportingDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentClient) UpdateInvoiceDocument(ctx context.Context, in *UpdateInvoiceDocumentRequest, opts ...grpc.CallOption) (*UpdateInvoiceDocumentResponse, error) {
	out := new(UpdateInvoiceDocumentResponse)
	err := c.cc.Invoke(ctx, "/Document/UpdateInvoiceDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentClient) UpdateSupportingDocument(ctx context.Context, in *UpdateSupportingDocumentRequest, opts ...grpc.CallOption) (*UpdateSupportingDocumentResponse, error) {
	out := new(UpdateSupportingDocumentResponse)
	err := c.cc.Invoke(ctx, "/Document/UpdateSupportingDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentServer is the server API for Document service.
// All implementations must embed UnimplementedDocumentServer
// for forward compatibility
type DocumentServer interface {
	StoreDocument(Document_StoreDocumentServer) error
	GetDocumentByReffNumber(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error)
	UpdateDocumentByReffNumber(context.Context, *UpdateDocumentRequest) (*UpdateDocumentResponse, error)
	DeleteDocumentByReffNumber(context.Context, *DeleteDocumentRequest) (*DeleteDocumentResponse, error)
	ListDocument(context.Context, *DocumentParameterRequest) (*ListServiceDocumentResponse, error)
	RevokeDocument(context.Context, *RevokeDocumentRequest) (*GetDocumentResponse, error)
	UploadFileService(Document_UploadFileServiceServer) error
	DownloadFileService(*DownloadFileRequest, Document_DownloadFileServiceServer) error
	GetInvoiceDocument(context.Context, *GetInvoiceDocumentRequest) (*GetInvoiceDocumentResponse, error)
	GetSupportingDocument(context.Context, *GetSupportingDocumentRequest) (*GetSupportingDocumentResponse, error)
	CreateInvoiceDocument(context.Context, *CreateInvoiceDocumentRequest) (*CreateInvoiceDocumentResponse, error)
	CreateSupportingDocument(context.Context, *CreateSupportingDocumentRequest) (*CreateSupportingDocumentResponse, error)
	UpdateInvoiceDocument(context.Context, *UpdateInvoiceDocumentRequest) (*UpdateInvoiceDocumentResponse, error)
	UpdateSupportingDocument(context.Context, *UpdateSupportingDocumentRequest) (*UpdateSupportingDocumentResponse, error)
	mustEmbedUnimplementedDocumentServer()
}

// UnimplementedDocumentServer must be embedded to have forward compatible implementations.
type UnimplementedDocumentServer struct {
}

func (UnimplementedDocumentServer) StoreDocument(Document_StoreDocumentServer) error {
	return status.Errorf(codes.Unimplemented, "method StoreDocument not implemented")
}
func (UnimplementedDocumentServer) GetDocumentByReffNumber(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDocumentByReffNumber not implemented")
}
func (UnimplementedDocumentServer) UpdateDocumentByReffNumber(context.Context, *UpdateDocumentRequest) (*UpdateDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDocumentByReffNumber not implemented")
}
func (UnimplementedDocumentServer) DeleteDocumentByReffNumber(context.Context, *DeleteDocumentRequest) (*DeleteDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDocumentByReffNumber not implemented")
}
func (UnimplementedDocumentServer) ListDocument(context.Context, *DocumentParameterRequest) (*ListServiceDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDocument not implemented")
}
func (UnimplementedDocumentServer) RevokeDocument(context.Context, *RevokeDocumentRequest) (*GetDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeDocument not implemented")
}
func (UnimplementedDocumentServer) UploadFileService(Document_UploadFileServiceServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadFileService not implemented")
}
func (UnimplementedDocumentServer) DownloadFileService(*DownloadFileRequest, Document_DownloadFileServiceServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadFileService not implemented")
}
func (UnimplementedDocumentServer) GetInvoiceDocument(context.Context, *GetInvoiceDocumentRequest) (*GetInvoiceDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInvoiceDocument not implemented")
}
func (UnimplementedDocumentServer) GetSupportingDocument(context.Context, *GetSupportingDocumentRequest) (*GetSupportingDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSupportingDocument not implemented")
}
func (UnimplementedDocumentServer) CreateInvoiceDocument(context.Context, *CreateInvoiceDocumentRequest) (*CreateInvoiceDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInvoiceDocument not implemented")
}
func (UnimplementedDocumentServer) CreateSupportingDocument(context.Context, *CreateSupportingDocumentRequest) (*CreateSupportingDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSupportingDocument not implemented")
}
func (UnimplementedDocumentServer) UpdateInvoiceDocument(context.Context, *UpdateInvoiceDocumentRequest) (*UpdateInvoiceDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateInvoiceDocument not implemented")
}
func (UnimplementedDocumentServer) UpdateSupportingDocument(context.Context, *UpdateSupportingDocumentRequest) (*UpdateSupportingDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSupportingDocument not implemented")
}
func (UnimplementedDocumentServer) mustEmbedUnimplementedDocumentServer() {}

// UnsafeDocumentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentServer will
// result in compilation errors.
type UnsafeDocumentServer interface {
	mustEmbedUnimplementedDocumentServer()
}

func RegisterDocumentServer(s grpc.ServiceRegistrar, srv DocumentServer) {
	s.RegisterService(&Document_ServiceDesc, srv)
}

func _Document_StoreDocument_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DocumentServer).StoreDocument(&documentStoreDocumentServer{stream})
}

type Document_StoreDocumentServer interface {
	SendAndClose(*UploadDocResponse) error
	Recv() (*UploadDocRequest, error)
	grpc.ServerStream
}

type documentStoreDocumentServer struct {
	grpc.ServerStream
}

func (x *documentStoreDocumentServer) SendAndClose(m *UploadDocResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *documentStoreDocumentServer) Recv() (*UploadDocRequest, error) {
	m := new(UploadDocRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Document_GetDocumentByReffNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServer).GetDocumentByReffNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Document/GetDocumentByReffNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServer).GetDocumentByReffNumber(ctx, req.(*GetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Document_UpdateDocumentByReffNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServer).UpdateDocumentByReffNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Document/UpdateDocumentByReffNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServer).UpdateDocumentByReffNumber(ctx, req.(*UpdateDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Document_DeleteDocumentByReffNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServer).DeleteDocumentByReffNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Document/DeleteDocumentByReffNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServer).DeleteDocumentByReffNumber(ctx, req.(*DeleteDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Document_ListDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocumentParameterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServer).ListDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Document/ListDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServer).ListDocument(ctx, req.(*DocumentParameterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Document_RevokeDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServer).RevokeDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Document/RevokeDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServer).RevokeDocument(ctx, req.(*RevokeDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Document_UploadFileService_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DocumentServer).UploadFileService(&documentUploadFileServiceServer{stream})
}

type Document_UploadFileServiceServer interface {
	SendAndClose(*UploadFileResponse) error
	Recv() (*UploadFileRequest, error)
	grpc.ServerStream
}

type documentUploadFileServiceServer struct {
	grpc.ServerStream
}

func (x *documentUploadFileServiceServer) SendAndClose(m *UploadFileResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *documentUploadFileServiceServer) Recv() (*UploadFileRequest, error) {
	m := new(UploadFileRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Document_DownloadFileService_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DocumentServer).DownloadFileService(m, &documentDownloadFileServiceServer{stream})
}

type Document_DownloadFileServiceServer interface {
	Send(*DownloadFileResponse) error
	grpc.ServerStream
}

type documentDownloadFileServiceServer struct {
	grpc.ServerStream
}

func (x *documentDownloadFileServiceServer) Send(m *DownloadFileResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Document_GetInvoiceDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInvoiceDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServer).GetInvoiceDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Document/GetInvoiceDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServer).GetInvoiceDocument(ctx, req.(*GetInvoiceDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Document_GetSupportingDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSupportingDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServer).GetSupportingDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Document/GetSupportingDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServer).GetSupportingDocument(ctx, req.(*GetSupportingDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Document_CreateInvoiceDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInvoiceDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServer).CreateInvoiceDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Document/CreateInvoiceDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServer).CreateInvoiceDocument(ctx, req.(*CreateInvoiceDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Document_CreateSupportingDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSupportingDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServer).CreateSupportingDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Document/CreateSupportingDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServer).CreateSupportingDocument(ctx, req.(*CreateSupportingDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Document_UpdateInvoiceDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInvoiceDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServer).UpdateInvoiceDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Document/UpdateInvoiceDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServer).UpdateInvoiceDocument(ctx, req.(*UpdateInvoiceDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Document_UpdateSupportingDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSupportingDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServer).UpdateSupportingDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Document/UpdateSupportingDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServer).UpdateSupportingDocument(ctx, req.(*UpdateSupportingDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Document_ServiceDesc is the grpc.ServiceDesc for Document service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Document_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Document",
	HandlerType: (*DocumentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDocumentByReffNumber",
			Handler:    _Document_GetDocumentByReffNumber_Handler,
		},
		{
			MethodName: "UpdateDocumentByReffNumber",
			Handler:    _Document_UpdateDocumentByReffNumber_Handler,
		},
		{
			MethodName: "DeleteDocumentByReffNumber",
			Handler:    _Document_DeleteDocumentByReffNumber_Handler,
		},
		{
			MethodName: "ListDocument",
			Handler:    _Document_ListDocument_Handler,
		},
		{
			MethodName: "RevokeDocument",
			Handler:    _Document_RevokeDocument_Handler,
		},
		{
			MethodName: "GetInvoiceDocument",
			Handler:    _Document_GetInvoiceDocument_Handler,
		},
		{
			MethodName: "GetSupportingDocument",
			Handler:    _Document_GetSupportingDocument_Handler,
		},
		{
			MethodName: "CreateInvoiceDocument",
			Handler:    _Document_CreateInvoiceDocument_Handler,
		},
		{
			MethodName: "CreateSupportingDocument",
			Handler:    _Document_CreateSupportingDocument_Handler,
		},
		{
			MethodName: "UpdateInvoiceDocument",
			Handler:    _Document_UpdateInvoiceDocument_Handler,
		},
		{
			MethodName: "UpdateSupportingDocument",
			Handler:    _Document_UpdateSupportingDocument_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StoreDocument",
			Handler:       _Document_StoreDocument_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "UploadFileService",
			Handler:       _Document_UploadFileService_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadFileService",
			Handler:       _Document_DownloadFileService_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/document.proto",
}
